import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ranges = [
  {
    name: 'Chilliwack Fish & Game Protective Association',
    slug: 'chilliwack-fish-game',
    address: '44000 Yale Rd W',
    city: 'Chilliwack',
    state: 'BC',
    zip: 'V2R 4H4',
    country: 'CA',
    lat: 49.1628,
    lng: -121.9544,
    maxDistanceYards: 200,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: true,
    steelTargetsAllowed: false,
    suppressorFriendly: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description: 'Local fish and game club with rifle and pistol ranges available to members.',
    status: 'ACTIVE',
  },
  {
    name: 'Silver Star Shooting Range',
    slug: 'silver-star-shooting-range',
    address: 'Silver Star Mountain',
    city: 'Vernon',
    state: 'BC',
    zip: 'V1B 3M1',
    country: 'CA',
    lat: 50.3592,
    lng: -119.0614,
    maxDistanceYards: 300,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    dayFeeAvailable: true,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: false,
    description: 'Outdoor shooting range in the BC Interior. Public access, multiple distances.',
    status: 'ACTIVE',
  },
  {
    name: 'Kamloops Rifle and Revolver Club',
    slug: 'kamloops-rifle-revolver-club',
    address: '955 Holt St',
    city: 'Kamloops',
    state: 'BC',
    zip: 'V2H 1G6',
    country: 'CA',
    lat: 50.6745,
    lng: -120.3273,
    maxDistanceYards: 600,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: ['F-Class', 'Benchrest'],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description:
      "One of BC's premier rifle clubs, with ranges from 100 to 600 yards. Hosts F-Class and benchrest competitions.",
    status: 'ACTIVE',
  },
  {
    name: 'Bald Butte Shooting Range',
    slug: 'bald-butte-shooting-range',
    address: 'Bald Butte Rd',
    city: 'Idaho Falls',
    state: 'ID',
    zip: '83401',
    country: 'US',
    lat: 43.5406,
    lng: -112.0341,
    maxDistanceYards: 1000,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    dayFeeAvailable: false,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: false,
    description:
      'Public BLM land shooting area outside Idaho Falls. Open to 1000 yards. Bring your own targets.',
    status: 'ACTIVE',
  },
  {
    name: 'Palisades Creek Shooting Range',
    slug: 'palisades-creek-shooting-range',
    address: 'Palisades Creek Rd',
    city: 'Swan Valley',
    state: 'ID',
    zip: '83449',
    country: 'US',
    lat: 43.4088,
    lng: -111.2756,
    maxDistanceYards: 600,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    description: 'USFS managed shooting range near Swan Valley. Multiple shooting distances up to 600 yards.',
    status: 'ACTIVE',
  },
  {
    name: 'Lethbridge Rifle and Revolver Club',
    slug: 'lethbridge-rifle-revolver-club',
    address: 'Range Rd 21-4',
    city: 'Lethbridge',
    state: 'AB',
    zip: 'T1J 4P4',
    country: 'CA',
    lat: 49.739,
    lng: -112.848,
    maxDistanceYards: 600,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: ['PRS', 'F-Class'],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: false,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description: 'Active shooting club in southern Alberta hosting precision rifle and F-Class events.',
    status: 'ACTIVE',
  },
]

async function main() {
  console.log('Seeding ranges...')
  for (const r of ranges) {
    await prisma.range.upsert({
      where: { slug: r.slug },
      create: r,
      update: r,
    })
  }
  console.log(`Seeded ${ranges.length} ranges`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
