import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ranges = [
  {
    name: 'Chilliwack Fish & Game Protective Association',
    slug: 'chilliwack-fish-game',
    address: '44000 Yale Rd W',
    city: 'Chilliwack',
    state: 'BC',
    zip: 'V2R 4H4',
    country: 'CA',
    lat: 49.1628,
    lng: -121.9544,
    maxDistanceYards: 200,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: true,
    steelTargetsAllowed: false,
    suppressorFriendly: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description: 'Local fish and game club with rifle and pistol ranges available to members.',
    status: 'ACTIVE',
  },
  {
    name: 'Silver Star Shooting Range',
    slug: 'silver-star-shooting-range',
    address: 'Silver Star Mountain',
    city: 'Vernon',
    state: 'BC',
    zip: 'V1B 3M1',
    country: 'CA',
    lat: 50.3592,
    lng: -119.0614,
    maxDistanceYards: 300,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    dayFeeAvailable: true,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: false,
    description: 'Outdoor shooting range in the BC Interior. Public access, multiple distances.',
    status: 'ACTIVE',
  },
  {
    name: 'Kamloops Rifle and Revolver Club',
    slug: 'kamloops-rifle-revolver-club',
    address: '955 Holt St',
    city: 'Kamloops',
    state: 'BC',
    zip: 'V2H 1G6',
    country: 'CA',
    lat: 50.6745,
    lng: -120.3273,
    maxDistanceYards: 600,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: ['F-Class', 'Benchrest'],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description:
      "One of BC's premier rifle clubs, with ranges from 100 to 600 yards. Hosts F-Class and benchrest competitions.",
    status: 'ACTIVE',
  },
  {
    name: 'Bald Butte Shooting Range',
    slug: 'bald-butte-shooting-range',
    address: 'Bald Butte Rd',
    city: 'Idaho Falls',
    state: 'ID',
    zip: '83401',
    country: 'US',
    lat: 43.5406,
    lng: -112.0341,
    maxDistanceYards: 1000,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    dayFeeAvailable: false,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: false,
    description:
      'Public BLM land shooting area outside Idaho Falls. Open to 1000 yards. Bring your own targets.',
    status: 'ACTIVE',
  },
  {
    name: 'Palisades Creek Shooting Range',
    slug: 'palisades-creek-shooting-range',
    address: 'Palisades Creek Rd',
    city: 'Swan Valley',
    state: 'ID',
    zip: '83449',
    country: 'US',
    lat: 43.4088,
    lng: -111.2756,
    maxDistanceYards: 600,
    rangeType: 'PUBLIC',
    surfaceTypes: [],
    matchTypes: [],
    membershipRequired: false,
    proneAllowed: true,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    description: 'USFS managed shooting range near Swan Valley. Multiple shooting distances up to 600 yards.',
    status: 'ACTIVE',
  },
  {
    name: 'Lethbridge Rifle and Revolver Club',
    slug: 'lethbridge-rifle-revolver-club',
    address: 'Range Rd 21-4',
    city: 'Lethbridge',
    state: 'AB',
    zip: 'T1J 4P4',
    country: 'CA',
    lat: 49.739,
    lng: -112.848,
    maxDistanceYards: 600,
    rangeType: 'CLUB',
    surfaceTypes: [],
    matchTypes: ['PRS', 'F-Class'],
    membershipRequired: true,
    proneAllowed: true,
    coveredPositions: false,
    steelTargetsAllowed: true,
    suppressorFriendly: true,
    hostsMatches: true,
    restroomsOnSite: true,
    parkingAvailable: true,
    description: 'Active shooting club in southern Alberta hosting precision rifle and F-Class events.',
    status: 'ACTIVE',
  },
]

const gunsmiths = [
  {
    name: 'Ryan Callahan',
    shopName: 'Cascade Precision Works',
    slug: 'cascade-precision-works',
    address: '45750 Yale Rd',
    city: 'Chilliwack',
    state: 'BC',
    country: 'CA',
    zip: 'V2P 2N4',
    lat: 49.1578,
    lng: -121.9512,
    primaryFocus: 'RIFLE',
    specialties: ['ACTION_TRUING', 'BARREL_WORK', 'CHASSIS_FITTING', 'BEDDING', 'CERAKOTE_RIFLE', 'REMINGTON_700', 'PRECISION_BUILD', 'SCOPE_MOUNTING'],
    platformsServiced: ['Remington 700', 'Tikka T3x', 'Savage 110', 'MDT Chassis'],
    calibersServiced: [],
    hasFfl: true,
    fflNumber: null,
    acceptsMailIn: true,
    avgTurnaroundWeeks: 6,
    turnaroundNotes: 'Currently 5–7 weeks on precision builds. Barrel work 2–3 weeks.',
    yearsExperience: 14,
    credentials: ['Brownells Armorer Certified'],
    rushJobsAvailable: false,
    bio: 'Precision rifle specialist in the Fraser Valley. Specialize in Remington 700 blueprinting, custom barrel fitting, and MDT chassis work. Built rifles that have won at the provincial level.',
    status: 'ACTIVE',
  },
  {
    name: 'Dave Hurst',
    shopName: 'Interior Arms',
    slug: 'interior-arms-kamloops',
    address: '1220 Battle St',
    city: 'Kamloops',
    state: 'BC',
    country: 'CA',
    zip: 'V2C 2N4',
    lat: 50.6731,
    lng: -120.3289,
    primaryFocus: 'GENERAL',
    specialties: ['BARREL_WORK', 'ACTION_TRUING', 'TRIGGER_JOBS_RIFLE', 'TRIGGER_JOBS_PISTOL', 'GLOCK_WORK', '1911_WORK', 'CERAKOTE_RIFLE', 'CERAKOTE_PISTOL', 'GENERAL_REPAIR', 'TRANSFERS', 'CLEANING_SERVICE'],
    platformsServiced: ['Remington 700', 'AR-15', 'Glock', '1911', 'Tikka T3x', 'Ruger 10/22'],
    calibersServiced: [],
    hasFfl: true,
    acceptsMailIn: true,
    avgTurnaroundWeeks: 4,
    turnaroundNotes: 'General repair and cleaning 1–2 weeks. Custom work 4–6 weeks.',
    yearsExperience: 22,
    rushJobsAvailable: true,
    fflAutoDownload: false,
    bio: 'Full-service gunsmith in Kamloops serving hunters, competitive shooters, and collectors for over 20 years. Rifles and handguns, warranty service for several major brands.',
    status: 'ACTIVE',
  },
  {
    name: 'Travis Kohl',
    shopName: 'Flatland Precision',
    slug: 'flatland-precision-lethbridge',
    address: '3217 26 Ave N',
    city: 'Lethbridge',
    state: 'AB',
    country: 'CA',
    zip: 'T1H 3R7',
    lat: 49.7128,
    lng: -112.8219,
    primaryFocus: 'RIFLE',
    specialties: ['PRECISION_BUILD', 'ACTION_TRUING', 'BARREL_WORK', 'CHAMBERING', 'CHASSIS_FITTING', 'BEDDING', 'SUPPRESSOR_HOST_WORK', 'MUZZLE_DEVICES', 'CERAKOTE_RIFLE', 'SCOPE_MOUNTING', 'REMINGTON_700', 'TIKKA_PLATFORM', 'SAVAGE_PLATFORM'],
    platformsServiced: ['Remington 700', 'Tikka T3x', 'Tikka T1x', 'Savage 110', 'Defiance Actions', 'MDT Chassis'],
    calibersServiced: [],
    hasFfl: false,
    acceptsMailIn: true,
    mailInOnly: false,
    avgTurnaroundWeeks: 8,
    turnaroundNotes: 'Full custom builds currently 10–12 weeks. Calling ahead strongly recommended.',
    yearsExperience: 9,
    credentials: ['Competed PRS 2019–2023', 'Brownells Trained'],
    rushJobsAvailable: false,
    bio: 'Former PRS competitor turned full-time gunsmith. Specialize in building accurate rifles from the ground up for hunters and long range competitors across Alberta. All work is test-fired before return.',
    status: 'ACTIVE',
  },
  {
    name: 'Mike Sorenson',
    shopName: 'Snake River Gun Works',
    slug: 'snake-river-gun-works',
    address: '1845 E 17th St',
    city: 'Idaho Falls',
    state: 'ID',
    country: 'US',
    zip: '83404',
    lat: 43.4912,
    lng: -112.0197,
    primaryFocus: 'GENERAL',
    specialties: ['BARREL_WORK', 'ACTION_TRUING', 'TRIGGER_JOBS_RIFLE', 'TRIGGER_JOBS_PISTOL', '1911_WORK', 'AR_BUILDS', 'AR_TRIGGER', 'AR_BARREL', 'SUPPRESSOR_HOST_WORK', 'NFA_TRANSFERS', 'TRANSFERS', 'CERAKOTE_RIFLE', 'CERAKOTE_PISTOL', 'GENERAL_REPAIR', 'CLEANING_SERVICE'],
    platformsServiced: ['AR-15', 'AR-10', 'Remington 700', 'Savage 110', '1911', 'Glock', 'Ruger', 'Winchester Model 70'],
    calibersServiced: [],
    hasFfl: true,
    fflLicenseType: 'TYPE_01',
    fflVerified: false,
    fflAutoDownload: false,
    acceptsMailIn: true,
    avgTurnaroundWeeks: 3,
    turnaroundNotes: 'Most work 2–4 weeks. AR builds and custom rifles 6–8 weeks.',
    yearsExperience: 17,
    credentials: ['US Army Veteran', 'Armorer Certified — Glock, Colt, Ruger'],
    rushJobsAvailable: true,
    bio: 'Full-service FFL gunsmith in Idaho Falls. Military background, certified on multiple platforms. Fast turnaround on most work. NFA transfers welcome.',
    status: 'ACTIVE',
  },
  {
    name: 'Jason Merritt',
    shopName: 'Merritt Competition Pistols',
    slug: 'merritt-competition-pistols',
    address: '8820 Chinden Blvd',
    city: 'Boise',
    state: 'ID',
    country: 'US',
    zip: '83714',
    lat: 43.6421,
    lng: -116.2895,
    primaryFocus: 'HANDGUN',
    specialties: ['1911_WORK', 'GLOCK_WORK', 'CZ_WORK', 'TRIGGER_JOBS_PISTOL', 'BARREL_FITTING_PISTOL', 'SLIDE_MILLING', 'FRAME_WORK', 'STIPPLING', 'SIGHT_INSTALLATION', 'CERAKOTE_PISTOL', 'COMPENSATOR_INSTALL', 'COMPETITION_PISTOL', 'CARRY_PISTOL_BUILD'],
    platformsServiced: ['1911', '2011', 'Glock', 'CZ Shadow 2', 'SIG P320', 'SIG P226', 'Beretta 92'],
    calibersServiced: [],
    hasFfl: true,
    fflLicenseType: 'TYPE_07',
    fflVerified: false,
    fflAutoDownload: true,
    acceptsMailIn: true,
    avgTurnaroundWeeks: 5,
    turnaroundNotes: 'Full 2011 builds 10–14 weeks. Trigger jobs and slide work 3–4 weeks.',
    yearsExperience: 12,
    credentials: ['USPSA Master Class', 'IDPA Expert'],
    rushJobsAvailable: false,
    bio: 'Handgun specialist focused exclusively on competition and carry pistol builds. USPSA Master class shooter. Known for 1911/2011 trigger work and custom Glock builds. Mail-in service nationwide.',
    status: 'ACTIVE',
  },
  {
    name: 'Glen Forde',
    shopName: 'NFA Solutions',
    slug: 'nfa-solutions-boise',
    address: '3455 S Gekeler Ln',
    city: 'Boise',
    state: 'ID',
    country: 'US',
    zip: '83706',
    lat: 43.5803,
    lng: -116.1872,
    primaryFocus: 'NFA',
    specialties: ['SUPPRESSOR_SERVICE', 'SUPPRESSOR_BUILD', 'SBR_CONVERSION', 'NFA_TRANSFERS', 'SUPPRESSOR_HOST_WORK', 'MUZZLE_DEVICES', 'FORM_1_BUILDS', 'MG_SERVICE'],
    platformsServiced: ['AR-15', 'AR-10', 'Remington 700', 'Ruger 10/22', 'MP5', 'AK Platform'],
    calibersServiced: [],
    hasFfl: true,
    fflLicenseType: 'SOT_02',
    fflVerified: false,
    fflAutoDownload: true,
    acceptsMailIn: true,
    avgTurnaroundWeeks: 2,
    turnaroundNotes: 'Most suppressor service within 1–2 weeks. SBR conversions 2–3 weeks.',
    yearsExperience: 8,
    credentials: ['SOT Class 2 Manufacturer', 'NFA Trust Specialist'],
    rushJobsAvailable: true,
    bio: "Idaho's NFA specialist. SOT Class 2 manufacturer. We handle suppressor builds, service and repair, SBR/SBS conversions, Form 1 builds, and all NFA item transfers. Walk-ins welcome.",
    status: 'ACTIVE',
  },
]

async function main() {
  console.log('Seeding ranges...')
  for (const r of ranges) {
    await prisma.range.upsert({
      where: { slug: r.slug },
      create: r,
      update: r,
    })
  }
  console.log(`Seeded ${ranges.length} ranges`)

  console.log('Seeding gunsmiths...')
  for (const g of gunsmiths) {
    await prisma.gunsmith.upsert({
      where: { slug: g.slug },
      create: { ...g, photos: [] },
      update: g,
    })
  }
  console.log(`Seeded ${gunsmiths.length} gunsmiths`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
